#!/usr/bin/env bash

# Run this file to install apps from the Mac App Store.
#
# This file assumes you have installed the Mac App Store command line interface
# named `mas` via https://github.com/mas-cli/mas

mas install 409907375  # Apple Remote Desktop
mas install 412522123  # BabyProof
mas install 687450044  # Blind - 1X Browser
mas install 1055511498 # Day One
mas install 1063631769 # Medis - GUI for Redis
mas install 1006739057 # NepTunes
mas install 409203825  # Numbers
mas install 693112260  # Sim Daltonism
mas install 1278508951 # Trello
mas install 1289378661 # Twitterrific 5 for Twitter
mas install 497799835  # Xcode
