#!/bin/bash

# Hide all opens apps
osascript '/Users/sean/Developer/dotfiles/clear-screen.AppleScript'

# Open all my daily-use Applications
open '/Applications/1Password.app'
open '/Applications/NepTunes.app'
open '/Applications/Slack.app'
open '/Applications/Toggl Track.app'
open '/Applications/Visual Studio Code - Insiders.app'
open '/System/Applications/Calendar.app'
open '/System/Applications/Mail.app'
open '/System/Applications/Messages.app'
open '/System/Applications/Music.app'
open '/System/Applications/Safari.app'

# Arrange the windows
osascript '/Users/sean/Developer/dotfiles/orgmode.AppleScript'
